# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Z1mVr3_UAhNUl_tGTdIijsOeO0Z712b
"""

#student information
# Function to accept student information
def accept_students():
    students = []
    for i in range(4):
        name = input("Enter student name: ")
        age = input("Enter student age: ")
        rollno = input("Enter student rollno:")
        students.append({"name": name, "age": age, "rollno": rollno})
    return students

# Function to display student information
def display_students(students):
    for student in students:
        print("Name:", student["name"])
        print("Age:", student["age"])
        print("rollno:", student["rollno"])
        print()

# Function to search for a student
def search_student(students, name):
    for student in students:
        if student["name"] == name:
            return student
    return None

# Function to delete a student
def delete_student(students, rollno):
    for student in students:
        if student["rollno"] == rollno:
            students.remove(student)
            return True
    return False

# Accept student information
students = accept_students()

# Display student information
display_students(students)

# Search for a student
search_name = input("Enter the name of the student to search for: ")
found_student = search_student(students, search_name)
if found_student:
    print("Student found:")
    print("Name:", found_student["name"])
    print("Age:", found_student["age"])
    print("rollno:", found_student["rollno"])
else:
    print("Student not found.")

# Delete a student
delete_rollno = input("Enter the rollno of the student to delete: ")
if delete_student(students, delete_rollno):
    print("Student deleted successfully.")
else:
    print("Student not found.")

# Display updated student information
display_students(students)